// Category Action Types
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const GET_SUBCATEGORIES_REQUEST = 'GET_SUBCATEGORIES_REQUEST';
export const GET_SUBCATEGORIES_SUCCESS = 'GET_SUBCATEGORIES_SUCCESS';
export const GET_SUBCATEGORIES_FAILURE = 'GET_SUBCATEGORIES_FAILURE';

// Product Action Types
export const GET_PRODUCTS_BY_CATEGORY_REQUEST = 'GET_PRODUCTS_BY_CATEGORY_REQUEST';
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS = 'GET_PRODUCTS_BY_CATEGORY_SUCCESS';
export const GET_PRODUCTS_BY_CATEGORY_FAILURE = 'GET_PRODUCTS_BY_CATEGORY_FAILURE';

// UI State Action Types
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';
export const SET_SELECTED_SUBCATEGORY = 'SET_SELECTED_SUBCATEGORY';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';

// Infinite Scroll Action Types
export const LOAD_MORE_PRODUCTS_BY_CATEGORY_REQUEST = 'LOAD_MORE_PRODUCTS_BY_CATEGORY_REQUEST';
export const LOAD_MORE_PRODUCTS_BY_CATEGORY_SUCCESS = 'LOAD_MORE_PRODUCTS_BY_CATEGORY_SUCCESS';
export const LOAD_MORE_PRODUCTS_BY_CATEGORY_FAILURE = 'LOAD_MORE_PRODUCTS_BY_CATEGORY_FAILURE';
export const SET_HAS_MORE_PRODUCTS = 'SET_HAS_MORE_PRODUCTS'; 