// Wishlist action types
export const FETCH_WISHLIST_REQUEST = 'FETCH_WISHLIST_REQUEST';
export const FETCH_WISHLIST_SUCCESS = 'FETCH_WISHLIST_SUCCESS';
export const FETCH_WISHLIST_FAILURE = 'FETCH_WISHLIST_FAILURE';

export const ADD_TO_WISHLIST_REQUEST = 'ADD_TO_WISHLIST_REQUEST';
export const ADD_TO_WISHLIST_SUCCESS = 'ADD_TO_WISHLIST_SUCCESS';
export const ADD_TO_WISHLIST_FAILURE = 'ADD_TO_WISHLIST_FAILURE';

export const REMOVE_FROM_WISHLIST_REQUEST = 'REMOVE_FROM_WISHLIST_REQUEST';
export const REMOVE_FROM_WISHLIST_SUCCESS = 'REMOVE_FROM_WISHLIST_SUCCESS';
export const REMOVE_FROM_WISHLIST_FAILURE = 'REMOVE_FROM_WISHLIST_FAILURE';

// Infinite Scroll Action Types
export const LOAD_MORE_WISHLIST_REQUEST = 'LOAD_MORE_WISHLIST_REQUEST';
export const LOAD_MORE_WISHLIST_SUCCESS = 'LOAD_MORE_WISHLIST_SUCCESS';
export const LOAD_MORE_WISHLIST_FAILURE = 'LOAD_MORE_WISHLIST_FAILURE';
export const RESET_WISHLIST = 'RESET_WISHLIST';
export const SET_HAS_MORE_WISHLIST = 'SET_HAS_MORE_WISHLIST';
